wucdbm_menu_builder_client_dashboard:
    path:        /
    defaults:    { _controller: WucdbmMenuBuilderClientBundle:Dashboard:dashboard }

wucdbm_menu_builder_client_menu:
    resource: routing/menu.yml
    prefix: /menus